### ISSUE TITLE
Provided tree file gives error when running SEPP

### ISSUE THREAD

**Issue by Syxas** [BKapili/ppit#2]
Thanks for making this tool available. However, I encounter an error when I run SEPP with the provided tree file nifH_reference_tree_v2.rda

I know this is an SEPP related issue, but my SEPP installation works for other tree files so I suspect it has something to do with the formating of the tree file provided with PPIT

I run SEPP 4.3.10, the version you recommend (4.3.5) is not available on the SEPP github, and the updates does not seem to be related to the core functions of SEPP.

This is the error message

```
dendropy.dataio.newickreader.NewickReaderMalformedStatementError: Error parsing data source '../PPIT/nifH_reference_tree_v2' on line 1 at column 152: Expecting ':', ')', ',' or ';' after reading label but found '}'
```

**Comment by bkapili** [comment]
Many thanks for your interest in PPIT!

The reference tree is included as a .rda file and needs to be converted to Newick-formatted tree file first. This can be done easily in R if you have the _ape_ package loaded:

`ape::write.tree(ppit::nifH_reference_tree_v2, file = "INSERT_DESIRED_PATH/nifH_reference_tree_v2.nwk")`

SEPP should be able to process this .nwk file properly!
